CREATE PROCEDURE [dbo].[spr_Parameter_GetAllParameter]
AS
BEGIN
	SET NOCOUNT ON  
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED  

	SELECT * FROM [Parameter] WHERE IsActive = 1;

	SET NOCOUNT OFF  
END