CREATE TABLE [dbo].[User]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	UserName VARCHAR(250) NOT NULL,
	[Password] VARCHAR(250) NOT NULL,
	FirstName VARCHAR(250) NOT NULL,
	LastName VARCHAR(250) NOT NULL,
	[Type] TINYINT NULL,
	CreatedDate DATETIME,
	ModifiedDate DATETIME,
	IsDeleted BIT NULL DEFAULT 0
)
