CREATE TABLE [dbo].[Order]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	OrderId VARCHAR(250),
	TotalPrice MONEY,
	OrderDate DATETIME,
	CreatedBy UNIQUEIDENTIFIER, 
    CONSTRAINT [FK_Order_User] FOREIGN KEY (CreatedBy) REFERENCES [User](Id)
)
