CREATE TABLE [dbo].[Order]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	OrderId VARCHAR(250),
	TotalPrice MONEY,
	OrderDate DATETIME,
	CreatedBy UNIQUEIDENTIFIER, 
	Customer_ID_FK UNIQUEIDENTIFIER, 
    CONSTRAINT [FK_Order_User] FOREIGN KEY (CreatedBy) REFERENCES [User](Id), 
    CONSTRAINT [FK_Order_Customer] FOREIGN KEY (Customer_ID_FK) REFERENCES [Customer](Id)
)
